microservice-chart:
  namespace: "pay-wallet"
  nameOverride: "b-pagopa-pay-wallet-event-dispatcher"
  fullnameOverride: "b-pagopa-pay-wallet-event-dispatcher"
  image:
    repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalleteventdispatcherservice
    tag: "0.1.2"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
    replicas: 6
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "itnuat.wallet.internal.uat.platform.pagopa.it"
    path: /blue/pagopa-wallet-event-dispatcher-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: { }
    name: ""
  podAnnotations: { }
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "900m"
  autoscaling:
    enable: true
    minReplica: 6
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    ENV: 'uat'
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    OTEL_SERVICE_NAME: "pagopa-payment-wallet-event-dispatcher-service-blue"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=uat"
    OTEL_EXPORTER_OTLP_ENDPOINT: "https://weuuat.kibana.internal.uat.platform.pagopa.it/apm"
    OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: otlp
    OTEL_TRACES_SAMPLER: "always_on"
    OTEL_INSTRUMENTATION_SPRING_SCHEDULING_ENABLED: "false"
    OTEL_INSTRUMENTATION_SPRING_INTEGRATION_ENABLED: "true"
    WALLET_STORAGE_QUEUE_ACCOUNT_NAME: pagopauitnpaywalletsa
    WALLET_STORAGE_QUEUE_ENDPOINT: https://pagopauitnpaywalletsa.queue.core.windows.net/pagopauitnpaywalletsa
    WALLET_USAGE_QUEUE_NAME: pagopa-u-itn-pay-wallet-usage-update-queue-b
    WALLET_SERVICE_URI: "http://b-pagopa-pay-wallet-microservice.pay-wallet.svc:8080/beta"
    WALLET_SERVICE_READ_TIMEOUT: "10000"
    WALLET_SERVICE_CONNECTION_TIMEOUT: "10000"
    WALLET_EXPIRATION_QUEUE_NAME: "pagopa-u-itn-pay-wallet-expiration-queue-b"
    AZURE_EVENTHUB_TOPIC_NAME: "payment-wallet-ingestion-dl-soak-test"
    AZURE_EVENTHUB_BOOTSTRAP_SERVER: "pagopa-u-itn-observ-evh.servicebus.windows.net:9093"
    CDC_SEND_RETRY_MAX_ATTEMPTS: "1"
    CDC_SEND_RETRY_INTERVAL_IN_MS: "1000"
    WALLET_CDC_QUEUE_NAME: "pagopa-u-itn-pay-wallet-cdc-queue-b"
    WALLET_CDC_QUEUE_POLLING_MAX_MESSAGE_PER_POLL: "80"
    WALLET_CDC_QUEUE_POLLING_FIXED_DELAY_MS: "1000"
  envSecret:
    OTEL_EXPORTER_OTLP_HEADERS: elastic-otel-token-header
    WALLET_STORAGE_QUEUE_KEY: wallet-storage-account-key
    AZURE_EVENTHUB_CONNECTION_STRING: sender-evt-tx-event-hub-connection-string-soak-test
  keyvault:
    name: "pagopa-u-pay-wallet-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: { }
  canaryDelivery:
    create: false
    ingress:
      create: false
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopauitncoreacr.azurecr.io/pagopapaymentwalleteventdispatcherservice
        tag: "latest"
        pullPolicy: Always
      envConfig:
        OTEL_SERVICE_NAME: "pagopa-payment-wallet-event-dispatcher-service-blue"
        WALLET_USAGE_QUEUE_NAME: "pagopa-u-itn-pay-wallet-usage-update-queue-b"
        WALLET_EXPIRATION_QUEUE_NAME: "pagopa-u-itn-pay-wallet-expiration-queue-b"
        WALLET_SERVICE_URI: "http://beta-pagopa-pay-wallet-microservice.pay-wallet.svc:8080"
      envSecret: { }
  tolerations:
    - effect: "NoSchedule"
      key: "paymentWalletOnly"
      operator: "Equal"
      value: "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: domain
                operator: In
                values:
                  - paywallet
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                aadpodidbinding: pay-wallet-pod-identity
            namespaces: [ "pay-wallet" ]
            topologyKey: topology.kubernetes.io/zone
